blog/urls.py
from django.urls import path
from . import views
from blog.apps import BlogConfig

app_name = BlogConfig.name


urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('post_detail/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('add_post/', views.PostCreateView.as_view(), name='add_post'),
    path('edit_post/<int:pk>', views.PostUpdateView.as_view(), name='edit_post'),
    path('delete_post/<int:pk>', views.PostDeleteView.as_view(), name='delete_post'),
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=250, verbose_name='Заголовок статьи')
    content = models.TextField(verbose_name='Содержание статьи')
    preview = models.ImageField(upload_to='images/', verbose_name='Изображение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    published = models.BooleanField(null=True)
    views_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['-created_at']

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.models import Post


class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    paginate_by = 3  # Количество постов на странице
    ordering = ['-created_at']  # Сортировка постов по дате создания в обратном порядке

    def get_queryset(self):  # фильтрация постов по опубликованным
        return Post.objects.filter(published=True)


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'

    def get_object(self, queryset=None):  # увеличение счетчика просмотров
        post = super().get_object()
        post.views_count += 1
        post.save()
        return post


class PostCreateView(CreateView):
    model = Post
    fields = ['title', 'content', 'preview']
    template_name = 'blog/post_form.html'
    success_url = reverse_lazy('blog:home')

    def form_valid(self, form): # изменение флага опубликованости при сохранении
        post = form.save(commit=True)
        post.published = True
        post.save()
        return super().form_valid(form)



class PostUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content', 'preview']
    template_name = 'blog/post_form.html'
    success_url = reverse_lazy('blog:post_detail')

    def get_success_url(self):
        post = self.get_object()
        return reverse_lazy('blog:post_detail', kwargs={'pk': post.pk})

    def form_valid(self, form):
        post = form.save(commit=True)
        post.published = True
        post.save()
        return super().form_valid(form)


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'blog/post_delete_confirm.html'
    success_url = reverse_lazy('blog:home')
    context_object_name = 'post'

blog/templates/blog/base.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Мой блог</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">

</head>
<body>
<header>
    {% include 'blog/includes/inc_menu.html' %}
</header>
<main>
    {% block content %}
    {% endblock %}
</main>
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
            <svg class="bi" width="30" height="24">
                <use xlink:href="#bootstrap"></use>
            </svg>
        </a>
        <span class="mb-3 mb-md-0 text-body-secondary">© 2025 Company, Inc</span>
    </div>
</footer>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/post_delete_confirm.html
{% extends 'blog/base.html' %}


{% block title %}Удаление поста{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="display-4 text-center">Удаление поста</h1>
            <form method="POST">
                {% csrf_token %}
                <p>Вы уверены, что хотите удалить пост "{{ post.title }}"?</p>

                <button type="submit" class="btn btn-danger">Удалить</button>
                <a href="{% url 'blog:home' %}" class="btn btn-secondary">Отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load my_tags %}


{% block title %}{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <p class="card-text">{{ post.content }}</p>
        <p class="card-text"><small class="text-body-secondary">Опубликовано: {{ post.created_at }}</small></p>
        <p class="card-text"><small class="text-body-secondary">Просмотров: {{ post.views_count }}</small></p>
        <a href="{% url 'blog:home' %}" class="btn btn-primary">Вернуться назад</a>
        <a href="{% url 'blog:edit_post' post.pk %}" class="btn btn-secondary">Редактировать</a>
        <a href="{% url 'blog:delete_post' post.pk %}" class="btn btn-danger">Удалить</a>
    </div>
    <img src="{{ post.preview | media_filter }}" class="card-img-bottom" alt="{{ post.title }}">
</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}


{% block title %}Форма поста{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="display-4 text-center">Форма поста</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a href="{% url 'blog:home' %}" class="btn btn-secondary">Отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load my_tags %}

{% block title %}Список постов{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="display-4 text-center">Список постов</h1>
            {% for post in posts %}
            <div class="card mb-3">
                <img src="{{ post.preview | media_filter }}" class="card-img-top" alt="{{ post.title }}">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content|truncatechars:100 }}</p>
                    <p class="card-text"><small class="text-body-secondary">{{ post.created_at }}</small></p>
                    <p class="card-text"><small class="text-body-secondary">{{ post.views_count }}</small></p>
                    <a href="{% url 'blog:post_detail' post.pk %}" class="btn btn-primary">Подробнее</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<center>
    {%if page_obj.has_previous %} {# whether the previous page exists #}
    <a href="?page={{page_obj.previous_page_number}}" class="btn btn-primary">Previous</a> {# link to the prev page #}
    {% endif %}
    <span class="btn btn-primary">{{page_obj.number}}</span> {# the current page number #}

    {%if page_obj.has_next %} {# whether the next page exists #}
    <a href="?page={{page_obj.next_page_number}}" class="btn btn-primary">Next</a> {# link to the next page #}
    {% endif %}
</center>
{% endblock %}