blog/urls.py
from django.urls import path
from . import views
from blog.apps import BlogConfig

app_name = BlogConfig.name


urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('post_detail/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('add_post/', views.PostCreateView.as_view(), name='add_post'),
    path('edit_post/<int:pk>', views.PostUpdateView.as_view(), name='edit_post'),
    path('delete_post/<int:pk>', views.PostDeleteView.as_view(), name='delete_post'),
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView, email_verification, UserProfileDetailView, UserProfileUpdateView

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='catalog:home'), name='logout'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),
    path('profile/<int:pk>/', UserProfileDetailView.as_view(), name='profile_detail'),
    path('profile/edit/<int:pk>/', UserProfileUpdateView.as_view(), name='edit_profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    token = models.CharField(max_length=100, verbose_name='Token', blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.EmailField):
                field.widget.attrs.update({"class": "form-control", "type": "email"})
            elif isinstance(field, forms.ImageField):
                field.widget.attrs.update({"class": "form-control", "type": "file"})
            else:
                field.widget.attrs.update({"class": "form-control"})


class CustomUserCreationForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'password1', 'password2')


class CustomUserEditForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'phone_number', 'avatar')

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        if phone_number and not phone_number.isdigit():
            raise forms.ValidationError('Номер телефона должен содержать только цифры.')
        return phone_number

users/views.py
import secrets
from django.shortcuts import get_object_or_404, redirect
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DetailView
from .forms import CustomUserCreationForm, CustomUserEditForm
from django.contrib.auth.mixins import LoginRequiredMixin
from config.settings import EMAIL_HOST_USER
from .models import CustomUser


class RegisterView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        user = form.save()
        user.is_active = False  # Ставим флаг активности на False для пользователя до подтверждения регистрации
        self.send_verification_email(user)  # Отправка подтверждения регистрации
        self.send_welcome_email(user.email)  # Отправка электронного письма с приветствием
        return super().form_valid(form)

    def send_welcome_email(self, user_email):
        # Отправка электронного письма с приветствием
        subject = 'Добро пожаловать в наш сервис'
        message = 'Спасибо, что зарегистрировались в нашем сервисе!'
        from_email = EMAIL_HOST_USER
        recipient_list = [user_email]
        send_mail(subject, message, from_email, recipient_list)

    def send_verification_email(self, user):
        # Отправка подтверждения регистрации
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject='Подтверждение регистрации',
            message=f'Для подтверждения регистрации перейдите по ссылке: {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email, ]
        )

def email_verification(request, token):
    user = get_object_or_404(CustomUser, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class UserProfileUpdateView(UpdateView):
    model = CustomUser
    form_class = CustomUserEditForm
    template_name = 'users/profile_edit.html'
    login_url = reverse_lazy("users:login")
    success_url = reverse_lazy('users:profile_detail')
    context_object_name = 'user'

    def get_success_url(self):
        return reverse('users:profile_detail', kwargs={'pk': self.kwargs['pk']})

class UserProfileDetailView(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = 'users/profile_detail.html'
    login_url = reverse_lazy("users:login")
    context_object_name = 'user'

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1 class="display-4 text-center">Вход</h1>
            <form method="POST" class="form-control">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary m-3">Войти</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title %}Профиль{% endblock %}

{% block content %}
<div class="container">
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
            <img src="{{ user.avatar | media_filter }}" class="img-fluid rounded-start" alt="{{user.email}}">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{ user.first_name }} {{ user.last_name }}</h5>
                <h6>Телефон: {{ user.phone_number }} </h6>
                <h6>Email: {{ user.email }}</h6>
                <p>Дата регистрации: {{ user.date_joined }}</p>
                <a href="{% url 'users:edit_profile' user.pk %}" class="btn btn-primary mt-3">Изменить профиль</a>
                <form method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger mt-3">Выйти</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile_edit.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title %}Редактировать профиль{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
          <h1 class="display-4 text-center">Редактировать профиль</h1>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary m-3">Сохранить изменения</button>
          </form>
          <a href="{% url 'users:profile_detail' user.pk %}" class="btn btn-secondary m-3">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1 class="display-4 text-center">Регистрация</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary m-3">Регистрация</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}