blog/urls.py
from django.urls import path
from . import views
from blog.apps import BlogConfig

app_name = BlogConfig.name


urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('post_detail/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('add_post/', views.PostCreateView.as_view(), name='add_post'),
    path('edit_post/<int:pk>', views.PostUpdateView.as_view(), name='edit_post'),
    path('delete_post/<int:pk>', views.PostDeleteView.as_view(), name='delete_post'),
    ]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig

from . import views

app_name = CatalogConfig.name

urlpatterns = [
    path("home/", views.ProductListView.as_view(), name="home"),
    path("contacts/", views.ContactTemplateView.as_view(), name="contacts"),
    path(
        "product_detail/<int:pk>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path("add_product", views.ProductCreateView.as_view(), name="add_product"),
    path(
        "edit_product/<int:pk>/", views.ProductUpdateView.as_view(), name="edit_product"
    ),
    path(
        "delete_product/<int:pk>/",
        views.ProductDeleteView.as_view(),
        name="delete_product",
    ),
    path("categories/", views.CategoryListView.as_view(), name="categories"),
    path("category/<int:pk>/", views.CategoryDetailView.as_view(), name="category_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import CustomUser


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name="Название категории")
    description = models.TextField(blank=True, verbose_name="Описание категории")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name="Название продукта")
    description = models.TextField(verbose_name="Описание продукта")
    stock = models.PositiveIntegerField(verbose_name="Количество в наличии")
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="Продукты"
    )
    image = models.ImageField(
        upload_to="images/", verbose_name="Изображение", blank=True
    )
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateField(auto_now=True, verbose_name="Дата изменения")
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="Владелец продукта", null=True, blank=True)
    is_publish = models.BooleanField(default=False, verbose_name="Опубликовать продукт?")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name"]
        permissions = [
            ("can_unpublish_product", "Can unpublish product"),
        ]

catalog/forms.py
import os

from django import forms
from dotenv import load_dotenv

from catalog.models import Product

load_dotenv()

FORBIDDEN_WORDS = os.getenv("FORBIDDEN_WORDS").split(", ")


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs.update({"class": "form-check-input"})
            else:
                field.widget.attrs.update({"class": "form-control"})


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "price", "stock", "image", "category", "is_publish"]

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price < 0:
            raise forms.ValidationError("Цена продукта не может быть отрицательной.")
        return price

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if any(word in name.lower() for word in FORBIDDEN_WORDS):
            raise forms.ValidationError("Имя продукта содержит запрещенные слова.")
        return name

    def clean_description(self):
        description = self.cleaned_data.get("description")
        if any(word in description.lower() for word in FORBIDDEN_WORDS):
            raise forms.ValidationError("Описание продукта содержит запрещенные слова.")
        return description

class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ["is_publish"]

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)

from catalog.models import Product, Category
from .services import CategoryService
from .forms import ProductForm, ProductModeratorForm


class CategoryListView(ListView):
    model = Category
    template_name = "catalog/categories_list.html"
    context_object_name = "categories"

class CategoryDetailView(DetailView):
    model = Category
    template_name = "catalog/category_detail.html"
    context_object_name = "category"
    def get_context_data(self, **kwargs):
        # Получаем объекты продуктов и категории
        products = CategoryService.get_products_from_category(category=self.object)
        categories = CategoryService.get_all_categories()
        return super().get_context_data(products=products, categories=categories, **kwargs)


class ProductListView(ListView):
    model = Product
    paginate_by = 3  # Количество продуктов на странице
    template_name = (
        "catalog/products_list.html"  # Имя шаблона для отображения списка продуктов
    )
    context_object_name = "products"

    def get_queryset(self):
        # Проверка наличия кэша
        cached_products = cache.get("products")
        if cached_products:
            return cached_products
        # Если кэша нет, получаем объекты из базы и кешируем их
        products = Product.objects.all()
        cache.set("products", products, 60 * 5)  # Кэширование на 5 минут
        user = self.request.user
        # фильтрация продуктов по опубликованным
        if user.has_perm("catalog.can_unpublish_product"):
            return Product.objects.all()
        return Product.objects.filter(is_publish=True)



@method_decorator(cache_page(60 * 5), name='dispatch')
class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = "catalog/product_detail.html"
    context_object_name = "product"
    login_url = reverse_lazy("users:login")


class ContactTemplateView(LoginRequiredMixin, TemplateView):
    template_name = "catalog/contacts.html"
    login_url = reverse_lazy("users:login")

    def get_context_data(self, **kwargs):
        if self.request.method == "POST":
            name = self.request.POST.get("name")
            phone = self.request.POST.get("phone")
            message = self.request.POST.get("message")
            print(name)
            print(phone)
            print(message)
            return HttpResponse("Сообщение отправлено!")


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_form.html"
    login_url = reverse_lazy("users:login")
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        product = form.save(commit=False)
        product.owner = self.request.user
        product.save()
        return redirect(reverse("catalog:home"))


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_form.html"
    login_url = reverse_lazy("users:login")
    success_url = reverse_lazy("catalog:home")

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        elif user.has_perm("catalog.can_unpublish_product"):
            return ProductModeratorForm


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = "catalog/product_delete_confirm.html"
    login_url = reverse_lazy("users:login")
    success_url = reverse_lazy("catalog:home")
    context_object_name = "product"

    def post(self, request, pk):
        product = get_object_or_404(Product, id=pk)
        if request.user == product.owner or request.user.has_perm("catalog.delete_product"):
            product.delete()
            return redirect(reverse("catalog:home"))
        else:
            return HttpResponseForbidden("У Вас нет прав на удаление продукта!")

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Магазин</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">

</head>
<body>
    <header>
        {% include 'catalog/includes/inc_menu.html' %}
    </header>
    <main>
    {% block content %}
    {% endblock %}
    </main>
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="{% url 'catalog:home' %}" class="nav-link px-2 text-body-secondary">Главная</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Каталог</a></li>
            <li class="nav-item"><a href="{% url 'catalog:add_product' %}" class="nav-link px-2 text-body-secondary">Добавить товар</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
            <li class="nav-item"><a href="{% url 'catalog:contacts' %}" class="nav-link px-2 text-body-secondary">Контакты</a></li>
        </ul>
        <p class="text-center text-body-secondary">© 2024 Company, Inc</p>
    </footer>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/categories_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title %}Список категорий{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="display-4 text-center">Список категорий</h1>
            {% for category in categories %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ category.name }}</h5>
                    <p class="card-text">Описание: {{ category.description }}</p>
                    <a href="{% url 'catalog:category_detail' category.pk %}" class="btn btn-primary">Просмотреть продукты</a>
                </div>
            </div>
            {% endfor %}
        </div>
{% endblock %}

catalog/templates/catalog/category_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title %}Список продуктов в категории{% endblock %}

{% block content %}
<h1 class="display-4 text-center">{{ category.name }}
<a href="{% url 'catalog:categories' %}" class="btn btn-outline-secondary"> <<< К списку категорий</a>
</h1>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for product in products %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ product.image | media_filter }}" class="card-img-top" alt="{{ product.name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.description|truncatechars:100 }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'catalog:product_detail' product.pk %}"
                               class="btn btn-sm btn-outline-secondary">Просмотр</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block title %}Контакты{% endblock %}

{% block content %}
<section class=" text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Контакты</h1>
        <p class="lead text-body-secondary">Контакты по которым можно связаться с нами.</p>
      </div>
    </div>
  </section>
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">Телефон</td>
                            <td>+7-777-77-77</td>
                        </tr>
                        <tr>
                            <td class="w-25">Почта</td>
                            <td>example@example.ru</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_delete_confirm.html
{% extends 'catalog/base.html' %}

{% block title %}Удалить продукт{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1 class="display-4 text-center">Удалить продукт</h1>
            <form method="POST">
                {% csrf_token %}
                <p>Вы уверены, что хотите удалить продукт "{{ product.name }}"?</p>

                <button type="submit" class="btn btn-danger">Удалить</button>
                <a href="{% url 'catalog:home' %}" class="btn btn-secondary">Отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title %}Информация о продукте{% endblock %}

{% block content %}
<div class="card m-3">
    <img src="{{ product.image | media_filter }}" class="card-img-top w-50" alt="{{ product.name }}">
    <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
        <p class="lead">Цена: {{ product.price }} руб.</p>
        <p class="card-text">{{ product.description }}</p>
        <p class="card-text">Категория: {{ product.category }}</p>
        <p class="card-text"><small class="text-body-secondary">Last updated {{ product.updated_at }}</small></p>
        <p class="card-text"><small class="text-body-secondary">Продавец: {{ product.owner }}</small></p>
        <a href="{% url 'catalog:home' %}" class="btn btn-primary">Вернуться назад</a>
        {% if perms.catalog.can_unpublish_product or user == product.owner %}
        <a href="{% url 'catalog:edit_product' product.pk %}" class="btn btn-secondary">Изменить</a>
        <a href="{% url 'catalog:delete_product' product.pk %}" class="btn btn-danger">Удалить</a>
        {% endif %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block title %}Добавить продукт{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            {% if object %}
            <h1 class="display-4 text-center">Редактировать продукт "{{ object.name }}"</h1>
            {% else %}
            <h1 class="display-4 text-center">Добавить продукт</h1>
            {% endif %}
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary m-3">Сохранить</button>
                <a href="{% url 'catalog:home' %}" class="btn btn-secondary m-3">Отменить</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/products_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title %}Список продуктов{% endblock %}

{% block content %}
<section class="py-1 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Магазин</h1>
            <p class="lead text-body-secondary">Здесь можно купить или продать свой товар.</p>
        </div>
    </div>
</section>
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for product in products %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ product.image | media_filter }}" class="card-img-top" alt="{{ product.name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.description|truncatechars:100 }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'catalog:product_detail' product.pk %}"
                               class="btn btn-sm btn-outline-secondary">Просмотр</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<center>
    {%if page_obj.has_previous %} {# whether the previous page exists #}
    <a href="?page={{page_obj.previous_page_number}}" class="btn btn-primary">Previous</a> {# link to the prev page #}
    {% endif %}
    <span class="btn btn-primary">{{page_obj.number}}</span> {# the current page number #}

    {%if page_obj.has_next %} {# whether the next page exists #}
    <a href="?page={{page_obj.next_page_number}}" class="btn btn-primary">Next</a> {# link to the next page #}
    {% endif %}
</center>
{% endblock %}